services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zabbix_ai_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app
    depends_on:
      - db
      - ollama

  db:
    image: alpine:3.18
    container_name: zabbix_ai_db
    restart: unless-stopped
    command: ["/bin/sh", "/init-db.sh"]
    volumes:
      - ./src/db:/db
      - ./init-db.sh:/init-db.sh:ro

  ollama:
    image: ollama/ollama
    container_name: zabbix_ai_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
