version: "3.9"
services:
  app:
    build: .
    container_name: zabbix_ai_app
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=http://zabbix_ai_ollama:11434
      - OLLAMA_MODEL=llama3.2
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: zabbix_ai_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    expose:
      - "11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_MODELS=llama3

volumes:
  ollama:
