version: "3.9"
services:
  app:
    build: .
    container_name: zabbix_ai_app
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=http://zabbix_ai_ollama:11434
      - OLLAMA_MODEL=llama3.2:3b
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - db
      - ollama

  db:
    image: alpine:3.18
    container_name: zabbix_ai_db
    restart: unless-stopped
    command: ["/bin/sh", "/init-db.sh"]
    volumes:
      - db_data:/db
      - ./init-db.sh:/init-db.sh:ro

  ollama:
    image: ollama/ollama
    container_name: zabbix_ai_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama


volumes:
  ollama:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./ollama
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db
